---
include:
  # Right part
  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_view_battery
    artifact-name: sofle_right
  # Left part
  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_left
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: sofle_left_reset_settings
